import { useEffect,useState } from "react";
import { FileUp,Hospital,LogOut,Plus,ShieldCheck,Stethoscope,Users } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { supabase } from "../lib/supabase";
import "../styles/portal.css";
export default function ClinicalPortal(){const nav=useNavigate();const [org,setOrg]=useState<any>(null);const [patients,setPatients]=useState<any[]>([]);const [msg,setMsg]=useState("");const [form,setForm]=useState({first_name:"",last_name:"",date_of_birth:"",medical_record_number:"",notes:""});const [file,setFile]=useState<File|null>(null);
 const load=async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:m}=await supabase.from("organization_members").select("organization_id").eq("user_id",user.id).eq("membership_status","active").limit(1).maybeSingle();if(!m){setMsg("No approved clinical organization is connected to this account.");return;}const {data:o}=await supabase.from("organizations").select("id,name,verification_status").eq("id",m.organization_id).single();setOrg(o);const {data:p}=await supabase.from("patients").select("*").eq("organization_id",m.organization_id).order("created_at",{ascending:false});setPatients(p||[])};useEffect(()=>{void load()},[]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!org)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:p,error}=await supabase.from("patients").insert({organization_id:org.id,family_owner_id:null,created_by:user.id,...form,date_of_birth:form.date_of_birth||null}).select("id").single();if(error){setMsg(error.message);return;}if(file&&p){const path=`${user.id}/${p.id}/${crypto.randomUUID()}.${file.name.split('.').pop()||'file'}`;const {error:u}=await supabase.storage.from("patient-documents").upload(path,file,{contentType:file.type});if(u){setMsg(`Patient created, but document upload failed: ${u.message}`);void load();return;}const {error:d}=await supabase.from("patient_documents").insert({patient_id:p.id,uploaded_by:user.id,storage_path:path,original_filename:file.name,mime_type:file.type,file_size_bytes:file.size,document_type:"medical_report"});if(d){await supabase.storage.from("patient-documents").remove([path]);setMsg(d.message);return;}}setMsg("Patient intake saved securely.");setForm({first_name:"",last_name:"",date_of_birth:"",medical_record_number:"",notes:""});setFile(null);void load()};
 return <main className="portal-shell clinical"><aside className="portal-side"><div className="portal-brand"><Stethoscope/>DMD-AI Hospital</div><nav><button className="active"><Hospital/>Clinical overview</button><button><Users/>Patients</button></nav><button className="portal-logout" onClick={async()=>{await supabase.auth.signOut();nav("/")}}><LogOut/>Sign out</button></aside><section className="portal-main"><header><div><span>VERIFIED CLINICAL WORKSPACE</span><h1>{org?.name||"Hospital Portal"}</h1><p>Structured patient intake for clinician review. AI analysis will be connected later as a decision-support layer.</p></div><div className="secure-pill"><ShieldCheck/>Approved access</div></header>{msg&&<div className="portal-message">{msg}</div>}<div className="portal-grid"><article className="portal-card"><h3>Patients</h3><strong className="big-number">{patients.length}</strong><p>Records in this organization workspace.</p></article><article className="portal-card"><h3>AI/ML</h3><strong>Not activated yet</strong><p>Clinical data collection comes before model integration.</p></article></div><section className="portal-section"><div className="section-title"><div><span>INITIAL CLINICAL INTAKE</span><h2>Add a patient</h2></div></div><form className="clinical-form" onSubmit={submit}><label>First name<input required value={form.first_name} onChange={e=>setForm({...form,first_name:e.target.value})}/></label><label>Last name<input required value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})}/></label><label>Date of birth<input type="date" value={form.date_of_birth} onChange={e=>setForm({...form,date_of_birth:e.target.value})}/></label><label>Medical record number<input value={form.medical_record_number} onChange={e=>setForm({...form,medical_record_number:e.target.value})}/></label><label className="wide">Clinical notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Presenting concerns or relevant context…"/></label><label className="upload-field wide"><FileUp/>Medical report (PDF/JPG/PNG, max 20 MB)<input type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={e=>setFile(e.target.files?.[0]||null)}/><span>{file?.name||"Choose document"}</span></label><button className="wide" type="submit"><Plus/>Save patient intake</button></form></section></section></main>}
