import {useEffect,useMemo,useState} from "react";
import {AlertTriangle,ArrowRight,BrainCircuit,CheckCircle2,ClipboardList,Dna,FileText,FileUp,FlaskConical,Hospital,LogOut,Plus,Search,ShieldCheck,UserRound,Users} from "lucide-react";
import {useNavigate} from "react-router-dom";
import {supabase} from "../lib/supabase";
import "../styles/clinicalPortal.css";
import "../styles/clinicalCareRequests.css";
import ClinicalCareRequests from "../components/ClinicalCareRequests";

type View="overview"|"requests"|"patients"|"screening"|"ml"|"labs"|"genetics"|"documents";
type Patient={id:string;first_name:string;last_name:string;date_of_birth?:string|null;medical_record_number?:string|null;notes?:string|null;created_at?:string};
type MlResult={predicted_class:number;model_probability:number;model_probability_percent:number;result_label:string;model_name:string;model_type:string;model_version:string;input_filename:string;input_probe_count:number;matched_selected_probe_count:number;required_selected_probe_count:number;validation_status:string;interpretation:string;warning:string};
type Screen={falls:boolean;stairs:boolean;rising:boolean;gowers:boolean;runJump:boolean;toeWalking:boolean;calf:boolean;weakness:boolean;motorDelay:boolean;loss:boolean;familyHistory:boolean;progressive:boolean;ck:string};
const blankScreen:Screen={falls:false,stairs:false,rising:false,gowers:false,runJump:false,toeWalking:false,calf:false,weakness:false,motorDelay:false,loss:false,familyHistory:false,progressive:false,ck:""};
const screeningItems:[keyof Screen,string][]=[["falls","Frequent unexplained falls"],["stairs","Difficulty climbing stairs"],["rising","Difficulty rising from floor or chair"],["gowers","Uses hands on legs to rise"],["runJump","Difficulty running or jumping"],["toeWalking","Toe walking"],["calf","Calf enlargement"],["weakness","Progressive muscle weakness"],["motorDelay","Delayed motor milestones"],["loss","Loss of a previously acquired motor ability"],["familyHistory","Family history compatible with dystrophinopathy"],["progressive","Symptoms worsening over time"]];

function ageYears(d?:string|null){if(!d)return null;const dob=new Date(d);if(Number.isNaN(dob.getTime()))return null;return Math.max(0,(Date.now()-dob.getTime())/31557600000)}
function assess(s:Screen,p?:Patient|null){
 const age=ageYears(p?.date_of_birth);let points=0;const reasons:string[]=[];
 const add=(key:keyof Screen,label:string,w:number)=>{if(s[key]){points+=w;reasons.push(label)}};
 add("gowers","Gowers-type manoeuvre reported",4);add("loss","Loss of a previously acquired motor ability",4);add("progressive","Progressive course reported",3);add("weakness","Progressive muscle weakness reported",3);add("falls","Frequent unexplained falls",2);add("stairs","Difficulty climbing stairs",2);add("rising","Difficulty rising",2);add("runJump","Difficulty running or jumping",2);add("toeWalking","Toe walking",1);add("calf","Calf enlargement",2);add("motorDelay","Delayed motor milestones",2);add("familyHistory","Relevant family history",2);
 const ck=Number(s.ck);if(Number.isFinite(ck)&&ck>0){if(ck>=2000){points+=5;reasons.push("Marked CK elevation entered")}else if(ck>=500){points+=2;reasons.push("CK elevation entered")}}
 if(age!==null&&age<10)points+=1;
 const level=points>=15?"High":points>=7?"Moderate":"Lower";
 const percent=Math.min(94,Math.max(8,Math.round(10+points*4.5)));
 return {points,level,percent,reasons};
}

export default function ClinicalPortal(){
 const nav=useNavigate();const [org,setOrg]=useState<any>(null);const [patients,setPatients]=useState<Patient[]>([]);const [view,setView]=useState<View>("overview");const [selectedId,setSelectedId]=useState("");const [search,setSearch]=useState("");const [msg,setMsg]=useState("");const [form,setForm]=useState({first_name:"",last_name:"",date_of_birth:"",medical_record_number:"",notes:""});const [file,setFile]=useState<File|null>(null);const [screen,setScreen]=useState<Screen>(blankScreen);const [result,setResult]=useState<ReturnType<typeof assess>|null>(null);
 const [mlModel,setMlModel]=useState<any>(null);const [mlChecked,setMlChecked]=useState(false);const [mlFile,setMlFile]=useState<File|null>(null);const [mlBusy,setMlBusy]=useState(false);const [mlError,setMlError]=useState("");const [mlResult,setMlResult]=useState<MlResult|null>(null);const [mlSaved,setMlSaved]=useState(false);
 const selected=patients.find(p=>p.id===selectedId)||patients[0]||null;
 const filtered=useMemo(()=>patients.filter(p=>`${p.first_name} ${p.last_name} ${p.medical_record_number||""}`.toLowerCase().includes(search.toLowerCase())),[patients,search]);
 const load=async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:m}=await supabase.from("organization_members").select("organization_id").eq("user_id",user.id).eq("membership_status","active").limit(1).maybeSingle();if(!m){setMsg("No approved clinical organization is connected to this account.");return}const {data:o}=await supabase.from("organizations").select("id,name,verification_status").eq("id",m.organization_id).single();setOrg(o);const {data:owned}=await supabase.from("patients").select("*").eq("organization_id",m.organization_id).order("created_at",{ascending:false});const {data:links}=await supabase.from("patient_organization_connections").select("patient_id").eq("organization_id",m.organization_id).eq("status","active");const linkedIds=(links||[]).map((x:any)=>x.patient_id).filter(Boolean);let connected:Patient[]=[];if(linkedIds.length){const {data:cp}=await supabase.from("patients").select("*").in("id",linkedIds);connected=(cp||[]) as Patient[]}const merged=[...((owned||[]) as Patient[]),...connected];const rows=Array.from(new Map(merged.map(p=>[p.id,p])).values());setPatients(rows);if(rows.length&&!selectedId)setSelectedId(rows[0].id)};
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(view!=="ml"||mlChecked)return;fetch(`/ml/dmd_molecular_model.json?t=${Date.now()}`).then(r=>{if(!r.ok)throw new Error("missing");return r.json()}).then(x=>setMlModel(x)).catch(()=>setMlModel(null)).finally(()=>setMlChecked(true))},[view,mlChecked]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!org)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:p,error}=await supabase.from("patients").insert({organization_id:org.id,family_owner_id:null,created_by:user.id,...form,date_of_birth:form.date_of_birth||null}).select("id").single();if(error){setMsg(error.message);return}if(file&&p){if(file.size>20*1024*1024){setMsg("The selected document is larger than 20 MB.");return}const path=`${user.id}/${p.id}/${crypto.randomUUID()}.${file.name.split(".").pop()||"file"}`;const {error:u}=await supabase.storage.from("patient-documents").upload(path,file,{contentType:file.type});if(u){setMsg(`Patient created, but document upload failed: ${u.message}`);void load();return}const {error:d}=await supabase.from("patient_documents").insert({patient_id:p.id,uploaded_by:user.id,storage_path:path,original_filename:file.name,mime_type:file.type,file_size_bytes:file.size,document_type:"medical_report"});if(d){await supabase.storage.from("patient-documents").remove([path]);setMsg(d.message);return}}setMsg("Patient record saved.");setForm({first_name:"",last_name:"",date_of_birth:"",medical_record_number:"",notes:""});setFile(null);await load();setView("patients")};
 const runAssessment=()=>{if(!selected){setMsg("Add or select a patient first.");return}setResult(assess(screen,selected));setMsg("")};
 const startScreen=(p?:Patient)=>{if(p)setSelectedId(p.id);setScreen(blankScreen);setResult(null);setView("screening")};
 const runMolecular=async()=>{if(!selected){setMlError("Select a patient first.");return}if(!mlFile){setMlError("Choose a compatible CSV expression profile first.");return}setMlBusy(true);setMlError("");setMlResult(null);setMlSaved(false);try{const fd=new FormData();fd.append("file",mlFile);const r=await fetch("http://127.0.0.1:8000/api/ml/dmd-molecular/predict",{method:"POST",body:fd});const body=await r.json().catch(()=>({}));if(!r.ok){const d=body?.detail;throw new Error(typeof d==="string"?d:(d?.message||"The molecular profile could not be analyzed."))}setMlResult(body as MlResult)}catch(e){setMlError(e instanceof Error?e.message:"The molecular profile could not be analyzed.")}finally{setMlBusy(false)}};
 const saveMlResult=async()=>{if(!mlResult||!selected||!org)return;setMlBusy(true);setMlError("");try{const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Your clinical session has expired.");const {error}=await supabase.from("dmd_ml_assessments").insert({patient_id:selected.id,organization_id:org.id,created_by:user.id,model_name:mlResult.model_name,model_type:mlResult.model_type,model_version:mlResult.model_version,predicted_class:mlResult.predicted_class,model_probability:mlResult.model_probability,result_label:mlResult.result_label,input_filename:mlResult.input_filename,input_probe_count:mlResult.input_probe_count,matched_selected_probe_count:mlResult.matched_selected_probe_count,required_selected_probe_count:mlResult.required_selected_probe_count,validation_status:mlResult.validation_status});if(error)throw error;setMlSaved(true)}catch(e){setMlError(e instanceof Error?e.message:"The result could not be saved.")}finally{setMlBusy(false)}};
 const signout=async()=>{await supabase.auth.signOut();nav("/")};
 const navItem=(id:View,label:string,Icon:any)=><button className={view===id?"active":""} onClick={()=>setView(id)}><Icon/>{label}</button>;
 return <main className="clinical-shell"><aside className="clinical-side"><div className="clinical-brand"><div><Dna/></div><span><b>DMD-AI</b><small>Clinical Workspace</small></span></div><div className="clinical-org"><ShieldCheck/><span><b>{org?.name||"Verified hospital"}</b><small>Verified clinical access</small></span></div><nav>{navItem("overview","Clinical Overview",Hospital)}{navItem("requests","Care Requests",ClipboardList)}{navItem("patients","Patients",Users)}{navItem("screening","DMD Screening",ClipboardList)}{navItem("ml","Molecular Analysis",BrainCircuit)}{navItem("labs","Laboratory Results",FlaskConical)}{navItem("genetics","Genetic Testing",Dna)}{navItem("documents","Reports & Documents",FileText)}</nav><button className="clinical-signout" onClick={signout}><LogOut/>Sign out</button></aside>
 <section className="clinical-main"><header className="clinical-header"><div><span>VERIFIED CLINICAL WORKSPACE</span><h1>{view==="overview"?"Clinical Overview":view==="requests"?"Care Requests":view==="patients"?"Patients":view==="screening"?"DMD Screening":view==="ml"?"Molecular Analysis":view==="labs"?"Laboratory Results":view==="genetics"?"Genetic Testing":"Reports & Documents"}</h1><p>{view==="screening"?"Review DMD-relevant clinical features and CK information before deciding the next clinical step.":view==="ml"?"Analyze molecular test data and review the result in clinical context.":"Patient-centered tools for screening, evidence review and longitudinal DMD care."}</p></div><div className="clinical-access"><ShieldCheck/>Approved access</div></header>{msg&&<div className="clinical-message">{msg}</div>}
 {view==="requests"&&<ClinicalCareRequests onOpenPatient={(patientId)=>{setSelectedId(patientId);void load();setView("patients")}}/>}
 {view==="overview"&&<><div className="clinical-kpis"><article><div><Users/></div><span>Total patients</span><strong>{patients.length}</strong><small>Organization records</small></article><article><div><ClipboardList/></div><span>DMD screening</span><strong>Ready</strong><small>Clinical feature review</small></article><article><div><FlaskConical/></div><span>CK & laboratory</span><strong>Review</strong><small>Use laboratory reference ranges</small></article><article><div><Dna/></div><span>Genetic testing</span><strong>Confirm</strong><small>DMD molecular evidence</small></article></div><div className="clinical-dashboard-grid"><section className="clinical-panel"><div className="clinical-panel-title"><div><span>PATIENT WORKLIST</span><h2>Recent patients</h2></div><button onClick={()=>setView("patients")}>View all <ArrowRight/></button></div>{patients.length?<div className="clinical-patient-list">{patients.slice(0,5).map(p=><button key={p.id} onClick={()=>{setSelectedId(p.id);setView("patients")}}><div className="clinical-avatar">{p.first_name?.[0]}{p.last_name?.[0]}</div><span><b>{p.first_name} {p.last_name}</b><small>{p.medical_record_number||"No record number"}</small></span><ArrowRight/></button>)}</div>:<div className="clinical-empty"><UserRound/><b>No patients yet</b><span>Add the first patient to begin the clinical workflow.</span><button onClick={()=>setView("patients")}><Plus/>Add patient</button></div>}</section><section className="clinical-panel clinical-workflow"><span>CLINICAL WORKFLOW</span><h2>From concern to confirmation</h2><div><i>1</i><span><b>Screen</b><small>History, motor features and examination findings</small></span></div><div><i>2</i><span><b>Review laboratory evidence</b><small>CK and relevant investigations</small></span></div><div><i>3</i><span><b>Confirm appropriately</b><small>DMD molecular genetic testing when indicated</small></span></div><button onClick={()=>startScreen()}><BrainCircuit/>Start DMD screening</button></section></div></>}
 {view==="patients"&&<><section className="clinical-panel"><div className="clinical-panel-title"><div><span>PATIENT RECORDS</span><h2>Patients</h2></div><label className="clinical-search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name or record number"/></label></div>{filtered.length?<div className="clinical-table"><div className="clinical-table-head"><span>Patient</span><span>Date of birth</span><span>Record number</span><span>Action</span></div>{filtered.map(p=><div className="clinical-table-row" key={p.id}><span className="patient-name"><div className="clinical-avatar">{p.first_name?.[0]}{p.last_name?.[0]}</div><b>{p.first_name} {p.last_name}</b></span><span>{p.date_of_birth?new Date(p.date_of_birth).toLocaleDateString():"Not recorded"}</span><span>{p.medical_record_number||"—"}</span><button onClick={()=>startScreen(p)}>Screen <ArrowRight/></button></div>)}</div>:<div className="clinical-empty"><Users/><b>No matching patients</b><span>Add a patient below or change the search.</span></div>}</section><section className="clinical-panel"><div className="clinical-panel-title"><div><span>PATIENT INTAKE</span><h2>Add patient</h2></div></div><form className="clinical-form" onSubmit={submit}><label>First name<input required value={form.first_name} onChange={e=>setForm({...form,first_name:e.target.value})}/></label><label>Last name<input required value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})}/></label><label>Date of birth<input type="date" value={form.date_of_birth} onChange={e=>setForm({...form,date_of_birth:e.target.value})}/></label><label>Medical record number<input value={form.medical_record_number} onChange={e=>setForm({...form,medical_record_number:e.target.value})}/></label><label className="wide">Clinical notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Presenting concerns and relevant clinical context"/></label><label className="upload-field wide"><FileUp/>Medical report (PDF/JPG/PNG, max 20 MB)<input type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={e=>setFile(e.target.files?.[0]||null)}/><span>{file?.name||"Choose document"}</span></label><button className="wide" type="submit"><Plus/>Save patient</button></form></section></>}
 {view==="screening"&&<section className="clinical-screen-grid"><div className="clinical-panel"><div className="clinical-panel-title"><div><span>DMD CLINICAL SCREENING</span><h2>Clinical feature review</h2></div></div><label className="clinical-select">Patient<select value={selected?.id||""} onChange={e=>{setSelectedId(e.target.value);setResult(null)}}><option value="">Select patient</option>{patients.map(p=><option key={p.id} value={p.id}>{p.first_name} {p.last_name}</option>)}</select></label><div className="screen-checks">{screeningItems.map(([key,label])=><label key={String(key)}><input type="checkbox" checked={Boolean(screen[key])} onChange={e=>{setScreen({...screen,[key]:e.target.checked});setResult(null)}}/><span><CheckCircle2/>{label}</span></label>)}</div><label className="ck-field"><span>Creatine kinase (CK), U/L <small>optional</small></span><input type="number" min="0" value={screen.ck} onChange={e=>{setScreen({...screen,ck:e.target.value});setResult(null)}} placeholder="Enter reported CK value"/><small>Interpret using the reporting laboratory's age-appropriate reference interval.</small></label><button className="clinical-primary" onClick={runAssessment}><BrainCircuit/>Analyze screening pattern</button></div><aside className="clinical-panel clinical-result">{result?<><span>SCREENING RESULT</span><div className={`risk-orb ${result.level.toLowerCase()}`}><strong>{result.percent}%</strong><small>{result.level} pattern</small></div><h2>{result.level} DMD screening signal</h2><p>The entered clinical pattern has {result.level.toLowerCase()} overlap with features that can raise suspicion for a dystrophinopathy.</p><div className="result-reasons">{result.reasons.slice(0,6).map(x=><div key={x}><CheckCircle2/>{x}</div>)}</div><div className="clinical-warning"><AlertTriangle/><p><b>This is not a diagnosis.</b> The percentage is a transparent screening score from the entered features, not a validated probability that this patient has DMD.</p></div><div className="clinical-next"><b>Suggested clinical next step</b><p>{result.level==="High"?"Prompt neuromuscular evaluation and appropriate diagnostic testing should be considered.":result.level==="Moderate"?"Review the history and examination, consider CK and neuromuscular evaluation when clinically appropriate.":"Continue clinical evaluation. A lower screening signal does not rule out DMD or another neuromuscular condition."}</p></div></>:<div className="clinical-empty result-empty"><BrainCircuit/><b>Screening result appears here</b><span>Select a patient, enter observed findings, then analyze the pattern.</span></div>}</aside></section>}
 {view==="ml"&&<section className="clinical-panel clinical-ml">
   <div className="clinical-panel-title"><div><span>MOLECULAR ANALYSIS</span><h2>DMD molecular analysis</h2><p>Analyze a patient's molecular test data and review the result alongside their clinical findings.</p></div></div>
   {mlModel?<>
     <div className="ml-run-grid"><div className="ml-upload-card"><h3>Analyze molecular test data</h3><p>Select the patient and upload their molecular test file.</p><label className="clinical-select">Patient<select value={selected?.id||""} onChange={e=>{setSelectedId(e.target.value);setMlResult(null);setMlSaved(false)}}><option value="">Select patient</option>{patients.map(p=><option key={p.id} value={p.id}>{p.first_name} {p.last_name}</option>)}</select></label><label className="ml-file"><FileUp/><span><b>{mlFile?.name||"Choose molecular test file"}</b><small>CSV · maximum 25 MB</small></span><input type="file" accept=".csv,text/csv" onChange={e=>{setMlFile(e.target.files?.[0]||null);setMlResult(null);setMlError("");setMlSaved(false)}}/></label>{mlError&&<div className="ml-error"><AlertTriangle/>{mlError}</div>}<button className="clinical-primary" disabled={mlBusy||!mlFile||!selected} onClick={runMolecular}><BrainCircuit/>{mlBusy?"Analyzing…":"Run molecular analysis"}</button></div>
     <div className="ml-result-card">{mlResult?<><span>MOLECULAR ANALYSIS RESULT</span><strong className="ml-result-label">{mlResult.model_probability>=.8?"Strong DMD-associated molecular pattern":mlResult.model_probability>=.5?"DMD-associated molecular pattern detected":mlResult.model_probability>=.2?"Low DMD-associated molecular pattern":"Control-like molecular pattern"}</strong><p>{mlResult.model_probability>=.5?"The uploaded molecular profile shows a pattern associated with DMD. Review this result together with the patient's clinical findings and appropriate diagnostic testing.":"The uploaded molecular profile does not show a strong DMD-associated pattern. Review this result together with the patient's clinical findings and appropriate diagnostic testing."}</p><div className="clinical-warning"><AlertTriangle/><p>This analysis supports clinical review but does not confirm or exclude DMD. Appropriate clinical evaluation and diagnostic testing remain necessary.</p></div><button className="ml-save" disabled={mlBusy||mlSaved} onClick={saveMlResult}><CheckCircle2/>{mlSaved?"Saved to patient record":"Save result to patient record"}</button></>:<div className="clinical-empty ml-result-empty"><BrainCircuit/><b>No molecular result yet</b><span>Select a patient and upload their molecular test data to begin.</span></div>}</div></div>
   </>:mlChecked?<div className="clinical-empty ml-empty"><BrainCircuit/><b>Molecular analysis is unavailable</b><span>Please try again later or contact your system administrator.</span></div>:<div className="clinical-empty ml-empty"><BrainCircuit/><b>Preparing molecular analysis…</b></div>}
 </section>}
 {(view==="labs"||view==="genetics"||view==="documents")&&<section className="clinical-panel clinical-evidence"><div className="clinical-panel-title"><div><span>{view==="labs"?"LABORATORY EVIDENCE":view==="genetics"?"MOLECULAR EVIDENCE":"CLINICAL DOCUMENTS"}</span><h2>{view==="labs"?"Laboratory results":view==="genetics"?"Genetic testing":"Reports & documents"}</h2></div></div><div className="clinical-evidence-hero">{view==="labs"?<FlaskConical/>:view==="genetics"?<Dna/>:<FileText/>}<div><h3>{view==="labs"?"Review results in clinical context":view==="genetics"?"Record confirmatory DMD testing":"Keep supporting evidence with the patient record"}</h3><p>{view==="labs"?"CK can strongly support suspicion of a dystrophinopathy, but the laboratory reference interval, age, clinical findings and other investigations matter.":view==="genetics"?"Molecular testing of the DMD gene is central to establishing or confirming a dystrophinopathy and can identify deletions, duplications and sequence variants.":"Patient documents uploaded during intake remain attached to the organization's protected patient records."}</p></div></div><div className="clinical-warning"><ShieldCheck/><p>{view==="genetics"?"AI screening does not replace molecular genetic testing or professional variant interpretation.":"DMD-AI keeps screening support separate from confirmatory clinical evidence."}</p></div></section>}
 </section></main>}
