import {useEffect,useMemo,useState} from "react";
import {useNavigate} from "react-router-dom";
import {Building2,MapPin,ShieldCheck,LogOut,Search,CheckCircle2,Send,FileText,Users,Stethoscope} from "lucide-react";
import {supabase} from "../lib/supabase";
import "../styles/careFlow.css";

type ProviderOrg={id:string;name:string;country?:string;state_province?:string;city?:string};
export default function HospitalCareRequests(){
 const nav=useNavigate();const [rows,setRows]=useState<any[]>([]);const [selected,setSelected]=useState<any|null>(null);const [search,setSearch]=useState("");const [filter,setFilter]=useState("all");const [message,setMessage]=useState("");const [org,setOrg]=useState<ProviderOrg|null>(null);const [providerName,setProviderName]=useState("");const [update,setUpdate]=useState({title:"Consultation update",summary:"",followUp:""});
 const loadIdentity=async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const prof=await supabase.from("profiles").select("full_name,name").eq("id",user.id).maybeSingle();const pd=prof.data as any;setProviderName(pd?.full_name||pd?.name||user.email||"Verified provider");const mem=await supabase.from("organization_members").select("organization_id").eq("user_id",user.id).eq("membership_status","active").limit(1).maybeSingle();if(mem.data?.organization_id){const o=await supabase.from("organizations").select("id,name,country,state_province,city").eq("id",mem.data.organization_id).eq("verification_status","approved").maybeSingle();if(o.data)setOrg(o.data as ProviderOrg)}};
 const load=async()=>{const r=await supabase.from("dmd_care_requests").select("*").order("created_at",{ascending:false});if(!r.error)setRows(r.data||[])};
 useEffect(()=>{void loadIdentity();void load()},[]);
 const filtered=useMemo(()=>rows.filter(r=>(filter==="all"||r.status===filter)&&`${r.country} ${r.region} ${r.city} ${r.summary}`.toLowerCase().includes(search.toLowerCase())),[rows,filter,search]);
 const accept=async(r:any)=>{const {data:{user}}=await supabase.auth.getUser();if(!user||!org){setMessage("Verified hospital identity could not be loaded.");return}const patch={status:"accepted",assigned_provider_id:user.id,assigned_organization_id:org.id,provider_organization_name:org.name,provider_city:org.city||null,provider_country:org.country||null,accepted_at:new Date().toISOString(),provider_message:`${org.name} has accepted your care request.`};const x=await supabase.from("dmd_care_requests").update(patch).eq("id",r.id);if(!x.error){setMessage(`Request accepted by ${org.name}.`);await load();setSelected({...r,...patch})}else setMessage(x.error.message)};
 const sendUpdate=async()=>{if(!selected||!update.summary.trim()||!org)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const x=await supabase.from("dmd_provider_updates").insert({care_request_id:selected.id,family_owner_id:selected.family_owner_id,patient_id:selected.patient_id,provider_id:user.id,organization_id:org.id,provider_organization_name:org.name,provider_name:providerName,title:update.title,summary:update.summary,follow_up_at:update.followUp||null});if(!x.error){await supabase.from("dmd_care_requests").update({status:"follow_up",provider_message:update.summary,provider_organization_name:org.name}).eq("id",selected.id);setMessage("Professional update sent to the family.");setUpdate({title:"Consultation update",summary:"",followUp:""});await load()}else setMessage(x.error.message)};
 const signout=async()=>{await supabase.auth.signOut();nav("/")};
 return <main className="provider-shell"><aside className="provider-side"><div className="provider-brand"><Stethoscope/><div><b>DMD-AI</b><span>Provider Connection</span></div></div><div className="verified"><ShieldCheck/><div><b>{org?.name||"Verified provider workspace"}</b><span>{org?[org.city,org.state_province,org.country].filter(Boolean).join(", "):"Focused care requests only"}</span></div></div><nav><button className="active"><Users/> Care Requests</button></nav><div className="provider-philosophy"><Building2/><b>Not an EHR</b><p>DMD-AI connects families with care. Your hospital's existing clinical systems remain the source of formal hospital records.</p></div><button className="signout" onClick={signout}><LogOut/> Sign out</button></aside>
 <section className="provider-main"><header><div><span>DMD-AI CARE CONNECTION</span><h1>Family Care Requests</h1><p>Relevant consenting requests for your verified provider organization.</p></div></header>
 <div className="provider-tools"><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search country, region, city or concern"/></label><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All requests</option><option value="open">Open</option><option value="accepted">Accepted</option><option value="follow_up">Follow-up</option></select></div>
 <div className="provider-layout"><section className="request-list">{filtered.map(r=><button key={r.id} className={selected?.id===r.id?"selected":""} onClick={()=>{setSelected(r);setMessage("")}}><div className="request-top"><span className={`priority ${r.urgency}`}>{r.urgency}</span><small>{new Date(r.created_at).toLocaleDateString()}</small></div><h3><MapPin/> {r.city}{r.region?`, ${r.region}`:""}, {r.country}</h3><p>{r.summary}</p><div className="share-tags">{r.share_assessment&&<span>Assessment shared</span>}{r.share_medical_records&&<span>Medical shared</span>}{r.share_genetics&&<span>Genetics shared</span>}</div><small className="request-status">{r.status.replaceAll("_"," ")}</small></button>)}{!filtered.length&&<div className="care-empty-mini">No matching care requests for this verified provider.</div>}</section>
 <section className="provider-detail">{selected?<><div className="detail-head"><div><span>CARE REQUEST</span><h2>{selected.city}, {selected.country}</h2>{selected.provider_organization_name&&<small>Assigned to {selected.provider_organization_name}</small>}</div><span className={`priority ${selected.urgency}`}>{selected.urgency}</span></div><div className="detail-summary"><b>Family's reason for requesting help</b><p>{selected.summary}</p></div>
 <div className="privacy-panel"><ShieldCheck/><div><b>Consent-controlled information</b><p>Assessment: {selected.share_assessment?"Shared":"Not shared"} · Medical records: {selected.share_medical_records?"Shared":"Not shared"} · Genetics: {selected.share_genetics?"Shared":"Not shared"}</p></div></div>
 {selected.status==="open"&&<button className="care-primary" onClick={()=>accept(selected)}><CheckCircle2/> Accept care request</button>}
 {selected.status!=="open"&&<div className="provider-update"><h3>Send an update to the family</h3><p className="provider-identity-note"><Building2/> Sending as <b>{org?.name||"verified provider"}</b>{providerName?` · ${providerName}`:""}</p><label>Update title<input value={update.title} onChange={e=>setUpdate({...update,title:e.target.value})}/></label><label>Summary / instructions<textarea rows={5} value={update.summary} onChange={e=>setUpdate({...update,summary:e.target.value})} placeholder="Summarize the professional update, next steps, or instructions for the family."/></label><label>Follow-up date<input type="datetime-local" value={update.followUp} onChange={e=>setUpdate({...update,followUp:e.target.value})}/></label><button className="care-primary" onClick={sendUpdate}><Send/> Send family update</button></div>}
 {message&&<p className="care-saved">{message}</p>}</>:<div className="detail-empty"><FileText/><h2>Select a care request</h2><p>Open a request to review the family's concern and consent choices.</p></div>}</section></div></section></main>
}
