import {useEffect,useMemo,useState} from "react";
import {CheckCircle2,FileText,MapPin,Search,Users} from "lucide-react";
import {supabase} from "../lib/supabase";
export default function ClinicalCareRequests({onOpenPatient}:{onOpenPatient?:(patientId:string)=>void}){
 const [rows,setRows]=useState<any[]>([]),[selected,setSelected]=useState<any|null>(null),[search,setSearch]=useState(""),[filter,setFilter]=useState("all"),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const load=async()=>{const {data,error}=await supabase.from("dmd_care_requests").select("*").order("created_at",{ascending:false});if(!error){const r=data||[];setRows(r);setSelected((s:any)=>s?r.find((x:any)=>x.id===s.id)||s:null)}};
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>rows.filter(r=>(filter==="all"||r.status===filter)&&`${r.city||""} ${r.region||""} ${r.country||""} ${r.summary||""}`.toLowerCase().includes(search.toLowerCase())),[rows,filter,search]);
 const accept=async(r:any)=>{setBusy(true);setMessage("");const x=await supabase.rpc("accept_dmd_care_request_and_connect_patient",{p_request_id:r.id});setBusy(false);if(x.error){setMessage(x.error.message);return}setMessage("Care request accepted. The family member is now available in the Clinical Portal.");await load()};
 return <section className="ccr"><div className="clinical-panel-title"><div><span>CARE REQUESTS</span><h2>Family care requests</h2><p>Review requests from families seeking care.</p></div></div><div className="ccr-tools"><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search location or concern"/></label><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All requests</option><option value="open">Open</option><option value="accepted">Accepted</option><option value="follow_up">Follow-up</option></select></div><div className="ccr-layout"><div className="ccr-list">{filtered.map(r=><button key={r.id} className={selected?.id===r.id?"active":""} onClick={()=>{setSelected(r);setMessage("")}}><div><b><MapPin/>{r.city}{r.region?`, ${r.region}`:""}, {r.country}</b><small>{new Date(r.created_at).toLocaleDateString()}</small></div><p>{r.summary}</p><span>{String(r.status||"open").replaceAll("_"," ")}</span></button>)}{!filtered.length&&<div className="clinical-empty"><Users/><b>No care requests found</b><span>New family requests will appear here.</span></div>}</div><div className="ccr-detail">{selected?<><div className="ccr-detail-head"><div><span>REQUEST</span><h3>{selected.city}, {selected.country}</h3></div><em>{String(selected.status||"open").replaceAll("_"," ")}</em></div><div className="ccr-summary"><b>Reason for requesting help</b><p>{selected.summary}</p></div><div className="ccr-shared"><b>Information included</b><span>{[selected.share_assessment&&"Assessment",selected.share_medical_records&&"Medical records",selected.share_genetics&&"Genetics & testing"].filter(Boolean).join(" · ")||"No additional records"}</span></div>{selected.status==="open"?<button className="clinical-primary" disabled={busy} onClick={()=>accept(selected)}><CheckCircle2/>{busy?"Accepting…":"Accept care request"}</button>:<button className="clinical-primary" onClick={()=>onOpenPatient?.(selected.patient_id)}><Users/>Open patient record</button>}{message&&<p className="ccr-message">{message}</p>}</>:<div className="clinical-empty"><FileText/><b>Select a care request</b><span>Choose a request to review it.</span></div>}</div></div></section>
}