import {useEffect,useState} from "react";
import {CheckCircle2,MapPin,Send,ShieldCheck,Stethoscope} from "lucide-react";
import {supabase} from "../lib/supabase";
import "../styles/familyProfessionalCare.css";
type Help={country:string;region:string;city:string;urgency:string;summary:string;shareAssessment:boolean;shareMedical:boolean;shareGenetics:boolean};
const blankHelp:Help={country:"",region:"",city:"",urgency:"routine",summary:"",shareAssessment:true,shareMedical:false,shareGenetics:false};
export default function FamilyProfessionalCare({patientId,patientName}:{patientId:string;patientName?:string}){
 const [open,setOpen]=useState(false),[requests,setRequests]=useState<any[]>([]),[updates,setUpdates]=useState<any[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[help,setHelp]=useState<Help>(blankHelp);
 const load=async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user||!patientId){setRequests([]);setUpdates([]);return}const [rq,up]=await Promise.all([supabase.from("dmd_care_requests").select("*").eq("family_owner_id",user.id).eq("patient_id",patientId).order("created_at",{ascending:false}).limit(5),supabase.from("dmd_provider_updates").select("*").eq("family_owner_id",user.id).eq("patient_id",patientId).order("created_at",{ascending:false}).limit(5)]);if(!rq.error)setRequests(rq.data||[]);if(!up.error)setUpdates(up.data||[])};
 useEffect(()=>{void load()},[patientId]);
 const send=async()=>{setMessage("");const {data:{user}}=await supabase.auth.getUser();if(!user||!patientId){setMessage("Select a family member first.");return}if(!help.country.trim()||!help.city.trim()||!help.summary.trim()){setMessage("Country, city and a short reason for help are required.");return}setBusy(true);const {error}=await supabase.from("dmd_care_requests").insert({family_owner_id:user.id,patient_id:patientId,country:help.country.trim(),region:help.region.trim(),city:help.city.trim(),urgency:help.urgency,summary:help.summary.trim(),share_assessment:help.shareAssessment,share_medical_records:help.shareMedical,share_genetics:help.shareGenetics,status:"open"});setBusy(false);if(error){setMessage(error.message);return}setMessage("Your care request has been sent.");setHelp(x=>({...x,summary:""}));setOpen(false);await load()};
 return <section className="fpc"><div className="fpc-head"><div className="fpc-title"><div><Stethoscope/></div><span><small>PROFESSIONAL CARE</small><h2>Get help from a hospital care team</h2><p>Send a care request for {patientName||"your family member"} and keep responses with their wellbeing record.</p></span></div><button type="button" onClick={()=>{setOpen(v=>!v);setMessage("")}}>{open?"Close":"Request professional help"}</button></div>
 {open&&<div className="fpc-form"><div className="fpc-location"><label>Country<input value={help.country} onChange={e=>setHelp({...help,country:e.target.value})}/></label><label>State / region<input value={help.region} onChange={e=>setHelp({...help,region:e.target.value})}/></label><label>City<input value={help.city} onChange={e=>setHelp({...help,city:e.target.value})}/></label></div><label>How soon do you need help?<select value={help.urgency} onChange={e=>setHelp({...help,urgency:e.target.value})}><option value="routine">Routine follow-up</option><option value="soon">Needs review soon</option><option value="priority">Priority review</option></select></label><label>What help do you need?<textarea rows={4} value={help.summary} onChange={e=>setHelp({...help,summary:e.target.value})}/></label><div className="fpc-share"><ShieldCheck/><div><b>Choose what to include</b><label><input type="checkbox" checked={help.shareAssessment} onChange={e=>setHelp({...help,shareAssessment:e.target.checked})}/> Latest assessment</label><label><input type="checkbox" checked={help.shareMedical} onChange={e=>setHelp({...help,shareMedical:e.target.checked})}/> Medical records</label><label><input type="checkbox" checked={help.shareGenetics} onChange={e=>setHelp({...help,shareGenetics:e.target.checked})}/> Genetics & testing</label></div></div><button className="fpc-send" disabled={busy} onClick={send}><Send/>{busy?"Sending…":"Send request"}</button></div>}
 {message&&<p className="fpc-message"><CheckCircle2/>{message}</p>}<div className="fpc-columns"><article><h3>Care requests</h3>{requests.length?requests.map(r=><div className="fpc-item" key={r.id}><MapPin/><span><b>{r.provider_organization_name||`${r.city}, ${r.country}`}</b><small>{r.summary}</small></span><em>{String(r.status||"open").replaceAll("_"," ")}</em></div>):<p className="fpc-empty">No care requests yet.</p>}</article><article><h3>Care updates</h3>{updates.length?updates.map(u=><div className="fpc-item" key={u.id}><CheckCircle2/><span><b>{u.title||"Care update"}</b><small>{u.summary}</small>{u.provider_organization_name&&<small>{u.provider_organization_name}</small>}</span></div>):<p className="fpc-empty">No care updates yet.</p>}</article></div></section>
}