import { CalendarDays, Dna, HeartHandshake, MessageCircleQuestion, ShieldCheck, Stethoscope, UsersRound } from "lucide-react";
import { useNavigate } from "react-router-dom";
import PublicNavbar from "../../components/public/PublicNavbar";
import familyHero from "../../assets/public/family-hero.jpg";
import "./PublicPages.css";

export default function ForFamilies(){
  const navigate=useNavigate();
  const choices=[
    [MessageCircleQuestion,"I’m worried about symptoms","Understand what the changes may mean and what to do next.","/#assistant"],
    [Stethoscope,"My child is being tested","Learn about tests, results and questions to ask your doctor.","#journey"],
    [ShieldCheck,"My child has DMD","Manage care, track changes, appointments and reports over time.","/signup"],
    [Dna,"I want to understand inheritance","Learn about genetics, carrier testing and family planning.","#genetics"],
    [CalendarDays,"Prepare for an appointment","Organize changes and questions into a doctor-ready summary.","#appointments"],
    [HeartHandshake,"Find DMD care & support","Explore reliable care and support resources.","/resources?category=support"],
  ] as const;
  const journey=[["1","Notice changes","You observe something that feels different."],["2","Understand","Organize what you have noticed."],["3","See a professional","Get evaluated by an appropriate clinician."],["4","Testing","A clinician orders the right investigations."],["5","Results","Understand clinician-confirmed findings."],["6","Ongoing care","Track changes and stay connected."]];
  const click=(to:string)=>{if(to.startsWith("#")){document.getElementById(to.slice(1))?.scrollIntoView({behavior:"smooth"})}else navigate(to)};
  return <main className="public-page"><PublicNavbar/>
    <section className="public-hero families-hero"><div className="public-section"><div><span className="public-kicker">Built for families</span><h1>You don’t have to understand everything. <em>We’re here to help.</em></h1><p>DMD-AI helps families organize changes they notice, prepare for medical care, understand clinician-confirmed information and stay informed through the DMD journey.</p><div className="public-hero-buttons"><button className="public-primary" onClick={()=>navigate("/#assistant")}>Tell DMD-AI what you’ve noticed</button><button className="public-secondary" onClick={()=>document.getElementById("journey")?.scrollIntoView({behavior:"smooth"})}>Explore the journey</button></div></div><div className="hero-image-shell"><img src={familyHero} alt="Parent supporting a child"/></div></div></section>
    <section className="public-section family-actions" id="symptoms"><h2 className="section-title">What are you here for?</h2><p className="section-subtitle">Choose what best describes your situation so DMD-AI can guide you to the right place.</p><div className="family-choice-grid">{choices.map(([Icon,title,desc,to])=><button className="choice-card" key={title} onClick={()=>click(to)}><span className="choice-icon"><Icon size={22}/></span><strong>{title}</strong><p>{desc}</p></button>)}</div></section>
    <section className="public-section journey-grid" id="journey"><article className="panel-card"><h2 className="section-title">From first concern to ongoing care</h2><p className="section-subtitle">Families report what they observe. Healthcare professionals examine, investigate and diagnose.</p><div className="journey-row">{journey.map(([n,t,d])=><div className="journey-step" key={n}><span>{n}</span><strong>{t}</strong><small>{d}</small></div>)}</div></article><article className="panel-card account-preview" id="tracking"><div><h2 className="section-title">Your child’s journey, all in one place</h2><p className="section-subtitle">Create an account to save family-reported changes, keep documents, prepare for appointments and share information when you choose.</p><div className="public-hero-buttons"><button className="public-primary" onClick={()=>navigate("/signup")}>Create free account</button><button className="public-secondary" onClick={()=>navigate("/login")}>Sign in</button></div></div><div className="mini-dashboard"><strong>Progress overview</strong><div className="mini-line purple"/><div className="mini-line"/><div className="mini-chart"/></div></article></section>
    <section className="public-section family-bottom-grid"><article className="soft-card" id="genetics"><Dna/><h3>Genetics & family planning</h3><p>Learn how X-linked inheritance works, why genetic counselling matters and when professional carrier testing may be appropriate.</p><button onClick={()=>navigate("/resources?category=understanding")}>Explore genetics →</button></article><article className="soft-card" id="appointments"><CalendarDays/><h3>Prepare for appointments</h3><p>Turn family observations into a clear summary of what changed, when it changed and what you want to ask the clinician.</p><button onClick={()=>navigate("/#assistant")}>Start a summary →</button></article><article className="soft-card" id="support"><UsersRound/><h3>You are not alone</h3><p>Find trusted educational resources, support organizations and practical guidance for families living with DMD.</p><button onClick={()=>navigate("/resources?category=support")}>Find support →</button></article></section>
  </main>;
}
